/* ──────────────────────────────────────────────────────────────
 * NURI · NAMESPACE CSS (BOX/STACK) FRESHNESS + VALUE HARNESS (the LIVE generated CSS · decision 74)
 *
 * The agnostic box + stack namespace CSS (packages/prototype/styles/{box,stack}.css) is now
 * GENERATED in place from the Field table (resolve-map.ts via pipeline/parsers/
 * namespace-css.js · run by `npm run build`) — decision 2 reversed for the namespace
 * layer (the L3c flip · N+38). The hand parity oracle RETIRED; this harness keeps the
 * GENERATED output honest: freshness (re-emit ≡ the committed file · Guards A/B), the
 * value chain (Guard C · the non-tautological independent oracle), and order-soundness
 * (Guards D + E).
 *
 * Five guards (node-only · the no-browser CI gate):
 *   A · STRUCTURAL ≡ — generated and hand carry the SAME @layer rules: the same
 *       selector set, each with the same declaration set (comments excepted ·
 *       order-insensitive · rule order differs [table order vs the hand's
 *       grouping] but is cascade-irrelevant here — every dispatch rule sets a
 *       disjoint property or a mutually-exclusive attribute value, asserted in
 *       Guard D). Identical (selector → declarations) ⇒ identical stylesheet ⇒
 *       identical computed style (CSS computed value is a pure function of the
 *       matched declarations) — so this is the core computed-style proof.
 *   B · RE-EMIT ≡ COMMITTED — the committed packages/prototype/styles/<ns>.css is exactly
 *       what the emitter produces now (the Guard-F freshness posture · re-run
 *       `npm run build`).
 *   C · RESOLVED-VALUE SPOT-CHECK — a curated cell set resolves through the REAL
 *       token CSS (styles/tokens-{primitive,semantic}.css · var() → final px) or
 *       carries the expected literal; asserted against an INDEPENDENT oracle (the
 *       design scale numbers · not read from hand). Confirms the generated CSS's
 *       indirection bottoms out at the right values. The logical→physical
 *       COMPUTED mapping (inline-size→width …) is the browser harness's job
 *       (pipeline/css-preview-computed-check.html · run via the preview tooling).
 *   D · ORDER-IRRELEVANCE — no two generated rules set the SAME property STRING to a
 *       DIFFERENT value via selectors that can co-match one element. Sound for stack +
 *       most of box, but BLIND to the shorthand/logical-longhand family that overlaps
 *       at the computed level (padding) — Guard E covers that.
 *   E · PADDING PRECEDENCE — the box padding family (padding · padding-inline/block ·
 *       the 4 edges) overlaps at the physical-longhand level; precedence (edge > axis >
 *       uniform · box.css) is achieved by SOURCE ORDER at equal specificity. Assert the
 *       generated rules touching each physical side are source-ordered uniform→axis→edge
 *       (so the edge wins). CLOSES the N+30-L3.1 Guard-D soundness gap — latent while the
 *       hand oracle stood (Guard A masked it), now the node gate's own guarantee since
 *       the oracle retired.
 *
 * Run:  node --test pipeline/css-preview.test.js   (or via `npm test`)
 * ────────────────────────────────────────────────────────────── */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';

import { generateAll } from './css-preview.js';
import { NS_SPECS } from './parsers/namespace-css.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..'); // packages/prototype
// The committed LIVE namespace CSS — GENERATED by `npm run build -w @nuri/prototype` into
// prototype's styles/ (N+41 · the A3 carve · was lib/components/<ns>/<ns>.css in spec before
// the carve). The freshness/structural guards compare the in-memory re-emit against it.
const liveCssPath = (ns) => resolve(PKG_ROOT, `styles/${ns}.css`);
// The token CSS (the scale vocab for Guard C's resolved-value oracle) is this prototype
// projection's OWN generated output now (N+62 · decision 80 · was @nuri/spec's styles/).
const TOKEN_STYLES = resolve(PKG_ROOT, 'generated/styles');

// ── parse a stylesheet's `@layer rules` → Map<selector, Map<prop,value>> ──
// postcss skips comment nodes for walkDecls/walkRules, so comments are excepted
// naturally. Multi-selector rules are split (defensive · box/stack have none).
// A duplicate (selector, prop) within one file is a parse-level surprise → throw.
function layerRuleMap(css, layer = 'rules') {
  const root = postcss.parse(css);
  const map = new Map();
  root.walkAtRules('layer', (at) => {
    if (at.params !== layer) return;
    at.walkRules((rule) => {
      for (const selRaw of rule.selector.split(',')) {
        const sel = selRaw.trim();
        if (!map.has(sel)) map.set(sel, new Map());
        const decls = map.get(sel);
        rule.walkDecls((d) => {
          if (decls.has(d.prop)) {
            throw new Error(`duplicate decl '${d.prop}' for '${sel}'`);
          }
          decls.set(d.prop, d.value.trim());
        });
      }
    });
  });
  return map;
}

// a stable, comparable string for a selector's declarations (order-insensitive).
const declSig = (declMap) =>
  [...declMap.entries()].map(([p, v]) => `${p}: ${v}`).sort().join('; ');

// ── source-ordered (selector, prop, value) triples from `@layer rules` ──
// Unlike layerRuleMap (keyed · order-insensitive), this preserves SOURCE ORDER — the
// input to Guard E's padding-family precedence check (the N+30 shorthand/longhand gap).
function orderedDecls(css) {
  const out = [];
  postcss.parse(css).walkAtRules('layer', (at) => {
    if (at.params !== 'rules') return;
    at.walkRules((rule) => {
      const sels = rule.selector.split(',').map((s) => s.trim());
      rule.walkDecls((d) => {
        for (const sel of sels) out.push({ sel, prop: d.prop, value: d.value.trim() });
      });
    });
  });
  return out;
}

// in-memory generation, once (one source, two readers · decision 48).
const generated = await generateAll();
const genByNs = new Map(generated.map((g) => [g.ns, g.css]));

// ══════════════════════════════════════════════════════════════════
// Guard A · STRUCTURAL ≡ (generated vs the hand oracle)
// ══════════════════════════════════════════════════════════════════
for (const { ns } of NS_SPECS) {
  test(`Guard A · ${ns}: re-emit ≡ committed ${ns}.css (structural)`, () => {
    const hand = layerRuleMap(readFileSync(liveCssPath(ns), 'utf8'));
    const gen = layerRuleMap(genByNs.get(ns));

    const handSels = [...hand.keys()].sort();
    const genSels = [...gen.keys()].sort();
    assert.deepEqual(
      genSels, handSels,
      `selector set differs.\n  only in hand: ${handSels.filter((s) => !gen.has(s)).join(' · ') || '∅'}` +
      `\n  only in generated: ${genSels.filter((s) => !hand.has(s)).join(' · ') || '∅'}`,
    );

    for (const sel of handSels) {
      assert.equal(
        declSig(gen.get(sel)), declSig(hand.get(sel)),
        `declarations differ for '${sel}'\n  hand:      ${declSig(hand.get(sel))}\n  generated: ${declSig(gen.get(sel))}`,
      );
    }

    // The empty `@layer tokens` is empty in both (mirrored) — zero rules either side.
    assert.equal(layerRuleMap(genByNs.get(ns), 'tokens').size, 0, 'generated @layer tokens should be empty');
    assert.equal(layerRuleMap(readFileSync(liveCssPath(ns), 'utf8'), 'tokens').size, 0, 'hand @layer tokens should be empty');
  });
}

// ══════════════════════════════════════════════════════════════════
// Guard B · RE-EMIT FRESHNESS (committed CSS == the emitter's output)
// ══════════════════════════════════════════════════════════════════
for (const { ns } of NS_SPECS) {
  test(`Guard B · ${ns}: committed packages/prototype/styles/${ns}.css is fresh (re-emit ≡ committed)`, () => {
    const committed = readFileSync(liveCssPath(ns), 'utf8');
    assert.equal(
      committed, genByNs.get(ns),
      `packages/prototype/styles/${ns}.css is stale — re-run \`npm run build\` (the namespace-CSS slice regenerates it)`,
    );
  });
}

// ══════════════════════════════════════════════════════════════════
// Guard C · RESOLVED-VALUE SPOT-CHECK (generated → final value · independent oracle)
// ══════════════════════════════════════════════════════════════════
// Build a var resolution map from the REAL token CSS, then resolve each curated
// cell's generated declaration to its final value and assert == the expected
// (the design scale numbers · NOT read from the hand CSS · so non-circular).
function buildVarMap() {
  const map = new Map();
  for (const f of ['tokens-primitive.css', 'tokens-semantic.css']) {
    const root = postcss.parse(readFileSync(resolve(TOKEN_STYLES, f), 'utf8'));
    root.walkDecls((d) => {
      if (d.prop.startsWith('--nuri-')) map.set(d.prop, d.value.trim());
    });
  }
  return map;
}
function resolveVarValue(value, varMap, depth = 0) {
  if (depth > 8) throw new Error(`var resolution too deep for '${value}'`);
  const m = value.match(/^var\((--[\w-]+)\)$/);
  const negative = value.match(/^calc\(-1 \* var\((--[\w-]+)\)\)$/);
  if (negative) {
    const next = varMap.get(negative[1]);
    if (next === undefined) throw new Error(`unresolved var ${negative[1]}`);
    const resolved = resolveVarValue(next.trim(), varMap, depth + 1);
    return resolved === '0' ? '0' : `-${resolved}`;
  }
  if (!m) return value; // a literal (12px · auto · center · 1 0 auto)
  const next = varMap.get(m[1]);
  if (next === undefined) throw new Error(`unresolved var ${m[1]}`);
  return resolveVarValue(next.trim(), varMap, depth + 1);
}

// Curated cells: [ns, selector, web-property, expected-final-value]. Spans every
// arm (scale·keyword·literal·flag·expand) + the logical-prop remap + the radius
// 9999 sentinel. Expected px are the design scale (space: xs4 sm6 md12 lg18 xl24
// · size: xs18 …3xl90 · radius: sm6 md12 lg18 full9999).
const CELLS = [
  ['box', '.nuri-box[data-width="md"]', 'inline-size', '36px'],          // scale·size·logical
  ['box', '.nuri-box[data-min-height="3xl"]', 'min-block-size', '90px'], // scale·size·full 7-leaf
  ['box', '.nuri-box[data-padding="lg"]', 'padding', '18px'],            // scale·space
  ['box', '.nuri-box[data-padding-x="xl"]', 'padding-inline', '24px'],   // scale·space·logical pad
  ['box', '.nuri-box[data-padding-start="sm"]', 'padding-inline-start', '6px'], // edge·logical
  ['box', '.nuri-box[data-radius="full"]', 'border-radius', '9999px'],   // scale·radius·sentinel
  ['box', '.nuri-box[data-radius-top="lg"]', 'border-start-start-radius', '18px'], // scaleMulti·radius·logical corner
  ['box', '.nuri-box[data-center="true"]', 'margin-inline', 'auto'],     // shell extra (literal)
  ['stack', '.nuri-stack[data-gap="md"]', 'gap', '12px'],                // scale·space
  ['stack', '.nuri-stack[data-align="center"]', 'align-items', 'center'],          // keyword
  ['stack', '.nuri-stack[data-justify="between"]', 'justify-content', 'space-between'], // keyword (renamed)
  ['stack', '.nuri-stack[data-direction="row"]', 'flex-direction', 'row'],         // literal
  ['stack', '.nuri-stack[data-wrap="true"]', 'flex-wrap', 'wrap'],                 // flag
  ['stack', '.nuri-stack[data-fill="grow"]', 'flex', '1 0 auto'],                  // expand (shorthand)
  ['stack', '.nuri-stack[data-fill="grow-shrink"]', 'min-inline-size', '0'],       // expand (logical min)
  ['stack', '.nuri-stack[data-fill="even"]', 'flex', '1 1 0'],                     // expand · the topbar edges (basis-0 equal split)
  ['stack', '.nuri-stack[data-fill="hug"]', 'inline-size', 'fit-content'],         // expand · cross-axis content clamp
  ['stack', '.nuri-stack[data-fill="hug"]', 'max-inline-size', '100%'],            // expand · bounded by the parent
  ['bleed', '.nuri-bleed[data-x="md"]', 'margin-inline', '-12px'],                // controlled negative inline space
  ['bleed', '.nuri-bleed[data-y="sm"]', 'margin-block', '-6px'],                  // controlled negative block space
  ['bleed', '.nuri-bleed[data-top="xl"]', 'margin-block-start', '-24px'],         // specific block-start edge
  ['bleed', '.nuri-bleed[data-bottom="lg"]', 'margin-block-end', '-18px'],        // specific block-end edge
];

test('Guard C · resolved-value spot-check (generated → final value)', () => {
  const varMap = buildVarMap();
  const maps = new Map(NS_SPECS.map(({ ns }) => [ns, layerRuleMap(genByNs.get(ns))]));
  for (const [ns, sel, prop, expected] of CELLS) {
    const rule = maps.get(ns).get(sel);
    assert.ok(rule, `no generated rule '${sel}'`);
    const raw = rule.get(prop);
    assert.ok(raw !== undefined, `'${sel}' has no '${prop}' declaration`);
    assert.equal(resolveVarValue(raw, varMap), expected, `${sel} { ${prop} } resolved`);
  }
});

test('Bleed shell owns fixed lift + measured-box containment without an authorable z channel', () => {
  const shell = layerRuleMap(genByNs.get('bleed')).get('.nuri-bleed');
  assert.ok(shell, 'generated Bleed shell exists');
  assert.deepEqual(Object.fromEntries(shell), {
    display: 'flex',
    'flex-direction': 'column',
    'flex-shrink': '0',
    position: 'relative',
    'z-index': '1',
  });
});

// ══════════════════════════════════════════════════════════════════
// Guard D · ORDER-IRRELEVANCE (the generated rule order cannot matter)
// ══════════════════════════════════════════════════════════════════
// The generated file emits FIELD rules in TABLE order; the hand file uses its
// own grouping. Guard A compares order-insensitively — sound ONLY if reordering
// the field rules cannot change a computed value. Field rules all key on
// `[data-<attr>="<value>"]`; within ONE attr the values are mutually exclusive
// (an element carries one value · only one rule matches), so the sole way order
// could bite is the SAME property dispatched by TWO DIFFERENT data-attrs that
// co-occur on a node. Assert that never happens: each field-dispatched property
// is owned by exactly one data-attr. (Shell rules carry no data-attr and are
// emitted shell-first in both files — their relative order already matches hand.)
for (const { ns } of NS_SPECS) {
  test(`Guard D · ${ns}: each dispatched property is owned by one data-attr (order cannot matter)`, () => {
    // Partition by CASCADE TARGET: a node rule (`.nuri-stack[data-x]`) and a child
    // rule (`.nuri-stack[data-y] > *`) style DIFFERENT elements, so the same property
    // dispatched by each never co-matches — no order dependence across the boundary.
    // (`fill` sets the node's own `flex`; `distribute`'s `> *` sets the CHILDREN's.)
    const attrsForProp = new Map(); // `${prop} ${target}` → Set<data-attr>
    for (const [sel, decls] of layerRuleMap(genByNs.get(ns))) {
      const attr = sel.match(/\[data-([\w-]+)=/)?.[1];
      if (!attr) continue; // shell base / element-wrapper rule
      const target = />\s*\*/.test(sel) ? 'child' : 'self';
      for (const prop of decls.keys()) {
        const key = `${prop} ${target}`;
        if (!attrsForProp.has(key)) attrsForProp.set(key, new Set());
        attrsForProp.get(key).add(attr);
      }
    }
    for (const [key, attrs] of attrsForProp) {
      const [prop, target] = key.split(' ');
      assert.equal(
        attrs.size, 1,
        `property '${prop}' (${target} target) is dispatched by >1 data-attr (${[...attrs].join(', ')}) — ` +
        `field-rule order could be cascade-significant, so Guard A's order-insensitive compare may be unsound`,
      );
    }
  });
}

// ══════════════════════════════════════════════════════════════════
// Guard E · PADDING PRECEDENCE (the shorthand/logical-longhand family · the N+30 gap closure)
// ══════════════════════════════════════════════════════════════════
// Guard D checks property STRINGS, blind to the box padding family that overlaps at the
// computed physical-longhand level: `padding` (uniform), `padding-inline`/`padding-block`
// (axis), and the 4 edges all cascade onto shared physical sides (padding + padding-inline-
// start both set padding-left). box.css documents precedence edge > axis > uniform, achieved
// by SOURCE ORDER at equal specificity (every dispatch rule is (0,2,0)). While the hand oracle
// stood, Guard A masked any divergence; the oracle RETIRED at L3c, so prove it directly: for
// each physical side, the generated rules touching it are source-ordered uniform→axis→edge
// (so the more-specific edge rule, emitted LATER, wins). A future BOX_FIELDS reorder that broke
// precedence keeps Guards A+D green but fails HERE (the N+30-L3.1 Guard-D gap, closed).
const PADDING_PHYSICAL = {
  'padding':              { tier: 0, sides: ['top', 'right', 'bottom', 'left'] }, // uniform
  'padding-inline':       { tier: 1, sides: ['left', 'right'] },                  // axis
  'padding-block':        { tier: 1, sides: ['top', 'bottom'] },                  // axis
  'padding-inline-start': { tier: 2, sides: ['left'] },                           // edge (LTR)
  'padding-inline-end':   { tier: 2, sides: ['right'] },                          // edge
  'padding-block-start':  { tier: 2, sides: ['top'] },                            // edge
  'padding-block-end':    { tier: 2, sides: ['bottom'] },                         // edge
};
test('Guard E · box: the padding family is source-ordered by precedence (uniform→axis→edge · the N+30 gap)', () => {
  const ordered = orderedDecls(genByNs.get('box')); // source-ordered (sel, prop, value) triples
  const bySide = { top: [], right: [], bottom: [], left: [] };
  ordered.forEach(({ prop }, idx) => {
    const fam = PADDING_PHYSICAL[prop];
    if (!fam) return;
    for (const side of fam.sides) bySide[side].push({ tier: fam.tier, idx, prop });
  });
  let sidesChecked = 0;
  for (const [side, entries] of Object.entries(bySide)) {
    if (entries.length < 2) continue; // a side touched by <2 padding props has no ordering hazard
    sidesChecked++;
    // entries are in source order (idx ascending) — assert precedence tiers non-decreasing.
    for (let i = 1; i < entries.length; i++) {
      assert.ok(
        entries[i].tier >= entries[i - 1].tier,
        `padding-${side}: '${entries[i].prop}' (precedence tier ${entries[i].tier}) is emitted AFTER ` +
        `'${entries[i - 1].prop}' (tier ${entries[i - 1].tier}) but is LESS specific — the more-specific ` +
        `padding rule must come LATER (source order at equal specificity decides the computed value). ` +
        `Reorder BOX_FIELDS so the padding family emits uniform → axis → edge.`,
      );
    }
  }
  assert.equal(sidesChecked, 4, `expected all 4 physical sides exercised by the box padding family, saw ${sidesChecked}`);
});

// ══════════════════════════════════════════════════════════════════
// distribute · the parent-side even split (childFill · the `> *` combinator)
// ══════════════════════════════════════════════════════════════════
// The WEB half of the cross-platform parity proof. `distribute:'even'` emits a
// child-combinator rule sizing every direct child to an equal share; the neutral
// FillCase it spells is STACK_FIELDS.distribute.cases.even — the SAME table RN's
// childFillStyle('even') reads (packages/rn/__tests__/stack-distribute.test.tsx).
// One source, two emits ⇒ "equal share on both" is honest, not asserted by eye.
test('distribute:even emits the child-fill combinator, derived from STACK_FIELDS.distribute (the RN-parity source)', async () => {
  const { loadTsDataFromPath } = await import('./parsers/strip.js');
  const RESOLVE_MAP = fileURLToPath(import.meta.resolve('@nuri/spec/resolve-map'));
  const { STACK_FIELDS } = await loadTsDataFromPath(RESOLVE_MAP);
  const even = STACK_FIELDS.distribute.cases.even; // { grow:1, shrink:1, basis:0, minInline:0 }

  const rules = layerRuleMap(genByNs.get('stack'));
  const sel = '.nuri-stack[data-distribute="even"] > *';
  assert.ok(rules.has(sel), `expected the distribute child-combinator rule '${sel}' in the generated stack CSS`);
  const decls = rules.get(sel);
  // web spells the neutral FillCase as `flex` + `min-inline-size` (expandWebDecls)
  assert.equal(decls.get('flex'), `${even.grow} ${even.shrink} ${even.basis}`, 'flex derives from the shared FillCase (grow shrink basis)');
  assert.equal(decls.get('min-inline-size'), String(even.minInline), 'min-inline-size derives from the shared FillCase minInline');
  // RN's childFillStyle('even') reads the SAME even case → { flexGrow:1, flexShrink:1,
  // flexBasis:0, minWidth:0 } (pinned in the RN suite). One table → equal share on both.
});
