/* ──────────────────────────────────────────────────────────────
 * NURI · TOKENS PARSER (Node) · ORCHESTRATOR
 * Reads styles/tokens-primitive.css → emits build/tokens.json (DTCG-
 * nested, colour primitive scope) AND walks styles/tokens-semantic.css
 * to emit build/tokens.ts (per-(accent × theme) resolved literals for
 * the migration agent + RN runtime).
 *
 * Lives at pipeline/tokens-parser.js — pipeline sources hand-
 * maintained, build/ outputs are 100% generated by this orchestrator
 * (decision 35 · N+6.0.4). Primitive logic lives in parsers/primitive.js;
 * semantic-cascade resolution + tokens.ts emitter live in
 * parsers/semantic.js; the per-component `@layer` walk + TokenPath union
 * live in parsers/components.js (the per-component FILE emit was retired
 * at Smell-1 · decision 66 arc #0). This file is the orchestrator and the
 * backwards-compatible re-export point for the existing primitive
 * round-trip tests.
 *
 * Companion to the browser parser at lib/docs/tokens.js — same shape,
 * different read environment (postcss vs document.styleSheets).
 *
 * See skills/pipeline-dtcg-export.md and docs/RISKS.md R2 for the
 * workstream context.
 * ────────────────────────────────────────────────────────────── */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
} from './parsers/primitive.js';

import {
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
} from './parsers/semantic.js';

import {
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
} from './parsers/components.js';

import { emitIconsTs, ICON_WEIGHTS } from './parsers/icons.js';

import { buildTypeScale, emitTypeTs, TYPE_SIZES } from './parsers/type.js';

import {
  buildInteraction,
  emitInteractionTs,
  INTERACTION_PRIMITIVES,
} from './parsers/interaction.js';

import {
  DESCRIPTOR_COMPONENTS,
  deriveDescriptor,
  emitDescriptorTs,
  emitDescriptorTsFromSource,
  emitDescriptorJsFromSource,
  docIrFromDescriptor,
  exportNameFor,
  emitSchemaTs,
} from './parsers/descriptors.js';

import {
  PALETTE_CONTRACT,
  derivePalette,
  emitPaletteTs,
} from './parsers/palette.js';

import { emitDocPage, buildDocTokenInputs } from './parsers/docs.js';

import { loadDimensions, flipDimensionCss } from './parsers/dimension-css.js';

import { loadColours, flipColourCss } from './parsers/colour-css.js';

import { loadSemanticColours, flipSemanticCss } from './parsers/semantic-css.js';

import { ICONS } from '../lib/components/icon/icons.js';

// Re-export so existing imports (and the primitive round-trip tests)
// keep working unchanged across the split.
export {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
  emitIconsTs,
  ICON_WEIGHTS,
  buildTypeScale,
  emitTypeTs,
  TYPE_SIZES,
  buildInteraction,
  emitInteractionTs,
  INTERACTION_PRIMITIVES,
  DESCRIPTOR_COMPONENTS,
  deriveDescriptor,
  emitDescriptorTs,
  emitDescriptorTsFromSource,
  emitDescriptorJsFromSource,
  docIrFromDescriptor,
  exportNameFor,
  emitSchemaTs,
  PALETTE_CONTRACT,
  derivePalette,
  emitPaletteTs,
  emitDocPage,
  buildDocTokenInputs,
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

const PRIMITIVE_CSS    = resolve(REPO_ROOT, 'styles/tokens-primitive.css');
const SEMANTIC_CSS     = resolve(REPO_ROOT, 'styles/tokens-semantic.css');
const DIMENSIONS_SRC   = resolve(REPO_ROOT, 'pipeline/dimensions.ts');
const COLOURS_SRC      = resolve(REPO_ROOT, 'pipeline/colours.ts');
const COMPONENTS_DIR   = resolve(REPO_ROOT, 'lib/components');
const JSON_OUT         = resolve(REPO_ROOT, 'build/tokens.json');
const TS_OUT           = resolve(REPO_ROOT, 'build/tokens.ts');
const INTERACTION_OUT  = resolve(REPO_ROOT, 'build/interaction.ts');
const TOKEN_PATHS_OUT  = resolve(REPO_ROOT, 'build/token-paths.ts');
const ICONS_OUT        = resolve(REPO_ROOT, 'build/icons.ts');
const DESCRIPTORS_OUT  = resolve(REPO_ROOT, 'build/descriptors');
const DESCRIPTORS_SRC  = resolve(REPO_ROOT, 'pipeline/descriptors');
const SCHEMA_SRC       = resolve(REPO_ROOT, 'pipeline/descriptors/schema.ts');
const PALETTE_OUT      = resolve(REPO_ROOT, 'build/palette.ts');
const DOCS_OUT         = resolve(REPO_ROOT, 'build/docs');

// Component sources whose doc page is GENERATED (N+22 · decision 66 arc #1 ·
// the website vertical slice). Generalized at N+23 (increment 2) from Button to
// the FULL DESCRIPTOR_COMPONENTS set — the descriptor-backed nav now covers all
// three ergonomic components (P11 · the old hand-written pages/components/*.html
// die incrementally as the generated pages cover them).
const DOC_COMPONENTS = ['composition-button', 'icon-avatar', 'topbar'];

// Component descriptors that ALSO emit a browser-ESM twin (decision 67 · the
// runtime web factory). The .js form lets a browser `import` the descriptor and
// resolve it with NO build step (zero-build · what Nuri IS #3). WIDENED at S4 to
// the FULL DESCRIPTOR_COMPONENTS set — the web factory now de-collapses all
// three frozen descriptors (Button at S3 · icon-avatar + topbar at S4), so each
// has a live consumer (P11 · decision 30 · no speculative emit ahead of one).
const BROWSER_DESCRIPTOR_COMPONENTS = ['composition-button', 'icon-avatar', 'topbar'];

// Per-component `@layer tokens` WALK list (decision 34 · N+6.0.3 ·
// extended at decisions 37 / 38 / 44). The per-component FILE emission
// (build/components/<name>.ts) is RETIRED — Smell-1 · decision 66
// arc #0: those files were consumed only by the now-retired
// `button-matrix` mirror (M4), and the lone live value — the
// decision-45 interaction baseline — moved to its own transversal emit
// at build/interaction.ts. The walk STAYS: it computes the per-component
// TokenPath coverage for the build log and keeps the resolver
// (readComponentTokens · resolveComponentValue) exercised end-to-end.
//
// N+36 · the pre-axes hand recipes (icon-button · list · list-item ·
// list-interactive-item · nav-item · switch · tab-bar · tabs ·
// typography-stack) were quarantined to legacy and dropped from this
// walk — the active set is now {primitives + the 3 descriptor recipes}.
// The walk feeds ONLY the build LOG (componentReports); it is independent
// of every build/ artefact (the TokenPath union derives from
// classifiedGroups · Slice 5), so the drop is build-output-neutral.
// Layout primitives (decision 37) · visual atoms like Icon (decision 38) ·
// 'palette' (N+19 B2b · decision 65.3 §6) carry an empty `@layer tokens`
// and contribute no paths; 'palette' emits its MAPPING through the
// dedicated Slice 7 below (build/palette.ts · pipeline/parsers/palette.js).
const COMPONENTS = ['button', 'stack', 'box', 'screen', 'scroll', 'spacer', 'icon', 'icon-avatar', 'separator', 'topbar', 'typography', 'palette'];

// Parse the orchestrator's CLI flag `--neutral=<scale>` from argv
// (decision 31). Default = DEFAULT_NEUTRAL. validateNeutral throws on
// unknown scales; no fallback, no env var — operator picked CLI-only
// in the post-N+5.7 thread. Manual parsing avoids a dependency for
// one flag.
export function parseArgs(argv) {
  const arg = argv.find((a) => a.startsWith('--neutral='));
  if (!arg) return DEFAULT_NEUTRAL;
  return validateNeutral(arg.slice('--neutral='.length));
}

async function main() {
  const neutral = parseArgs(process.argv);
  console.log(`[tokens-parser] data-neutral=${neutral}`);

  // ── Slice 0 · the dimension cascade · TS SoT → tokens-*.css (N+31 · decision 70 · the first flip) ──
  // decision 2 reverses for the dimension layer ONLY: the px scale + the
  // space/size/radius semantics are authored in pipeline/dimensions.ts (the
  // SoT) and WRITTEN INTO styles/tokens-{primitive,semantic}.css here, before
  // every downstream slice reads them. The emit is an in-place PASSTHROUGH —
  // only the dimension declarations' values are regenerated; all non-dimension
  // content (colours · the accent×theme cascade · border · type · font · the
  // reserved radius primitives) passes through verbatim (the S1 passthrough-
  // hybrid · no page repointing). Values are unchanged this slice, so every
  // slice below stays byte-identical → build/* byte-identical. Writing into
  // styles/ (a source dir) is the hybrid trade — muddier provenance for zero
  // repointing; the clean physical split is a later L3c-style cleanup.
  const dims = await loadDimensions(DIMENSIONS_SRC);
  await flipDimensionCss({ primitivePath: PRIMITIVE_CSS, semanticPath: SEMANTIC_CSS, dims });
  console.log(
    `[tokens-parser] flipped the dimension cascade from the TS SoT ` +
    `(${Object.keys(dims.px).length} px · ${Object.keys(dims.space).length} space · ` +
    `${Object.keys(dims.size).length} size · ${Object.keys(dims.radius).length} radius) → styles/tokens-*.css`,
  );

  // ── Slice 0 · the colour primitives · TS SoT → tokens-primitive.css (N+32 C1 · decision 70 · the second flip) ──
  // decision 2 reverses for the colour-PRIMITIVE layer (after the dimension layer
  // at N+31): the 7 neutral scales + lilac + the alpha scales are authored in
  // pipeline/colours.ts and WRITTEN INTO styles/tokens-primitive.css here, before
  // every downstream slice reads it. Same in-place PASSTHROUGH as the dimension
  // flip — only the --nuri-color-* declarations are regenerated; the accent×theme
  // cascade (tokens-semantic.css · decision 63) is NOT touched (that is C2). The
  // neutral resolution (--nuri-color-neutral-* → the active scale) is baked from
  // `neutral` (the --neutral flag · default cream) into ONE :root block — the
  // retired runtime [data-neutral] switcher, build-time selection only. At cream
  // the values are unchanged (tokens.ts already resolved cream since decision 31),
  // so build/* stays byte-identical; cream ≠ gray is a web-CSS-only change.
  const colours = await loadColours(COLOURS_SRC);
  await flipColourCss({ primitivePath: PRIMITIVE_CSS, colours, neutral });
  console.log(
    `[tokens-parser] flipped the colour primitives from the TS SoT ` +
    `(${Object.keys(colours.neutralScales).length} neutral scales · lilac · black/white alpha · ` +
    `neutral resolution → ${neutral}) → styles/tokens-primitive.css`,
  );

  // ── Slice 0 · the colour SEMANTIC cascade · TS SoT → tokens-semantic.css (N+32 C2 · decision 70 · the cascade) ──
  // decision 2 reverses for the colour SEMANTIC layer (the second half of the colour
  // vertical · after the primitives at C1) → it is now FULLY reversed for colour. The
  // accent×theme matrix (chrome + accent) is authored in pipeline/colours.ts and the
  // cascade is GENERATED into styles/tokens-semantic.css here (parsers/semantic-css.js):
  // the 8 blocks 1·2·3·4·4b·5·6·6b, INCLUDING the decision-63 #4b/#6b descendant-
  // combinator self-scope that no stock token tool emits. Unlike the dimension /
  // colour-primitive flips this is NOT a byte-identical passthrough — the cascade is
  // regenerated (terser · the resolution matrix moved to the SoT) — but it resolves to
  // the SAME (accent × theme) cross-product, so build/tokens.ts (the RN single-context
  // contract · decisions 27/62/63 · no cascade, no #4b/#6b) stays byte-identical. The
  // generated region replaces a marked span; the file header + the dimension blocks
  // (space/size/radius · Slice 0 above) pass through verbatim.
  const semanticColours = await loadSemanticColours(COLOURS_SRC);
  await flipSemanticCss({ semanticPath: SEMANTIC_CSS, semanticColours });
  console.log(
    `[tokens-parser] flipped the accent×theme cascade from the TS SoT ` +
    `(${Object.keys(semanticColours.chrome).length} chrome × {light,dark} · ` +
    `${Object.keys(semanticColours.accent).length} accent × {neutral,lilac} × {light,dark} · ` +
    `the dec-63 #4b/#6b self-scope) → styles/tokens-semantic.css`,
  );

  const primitiveCSS = await readFile(PRIMITIVE_CSS, 'utf8');
  const semanticCSS  = await readFile(SEMANTIC_CSS,  'utf8');

  // ── Slice 1 · colour-primitive DTCG JSON (N+3.5) ──────────────
  const primitives = await readPrimitives(primitiveCSS);
  const tree = buildDtcg(primitives, (v) => v.startsWith('--nuri-color-'));
  await mkdir(dirname(JSON_OUT), { recursive: true });
  await writeFile(JSON_OUT, JSON.stringify(tree, null, 2) + '\n', 'utf8');
  const jsonCount = countLeaves(tree);

  // ── Slice 2 · semantic-cascade → tokens.ts literals (N+5) ─────
  const primitiveMap = buildPrimitiveMap(primitiveCSS);
  const semanticRules = readSemanticRules(semanticCSS);
  const resolved = resolveSemanticCrossProduct(semanticRules, primitiveMap);
  // The `type` namespace joins tokens.ts as a directly-accessed,
  // context-invariant composite emitted from the --nuri-type-*
  // primitives (decision 54 · the icon model · one source, two
  // readers). It is appended after the cascade-resolved runtime
  // groups; it is NOT a runtime/TokenPath set.
  const typeScale = buildTypeScale(primitiveMap);
  const tsSource = emitTokensTs(resolved, semanticRules) + '\n' + emitTypeTs(typeScale);
  await writeFile(TS_OUT, tsSource, 'utf8');
  const classifiedGroups = classifyAll(semanticRules);
  const semanticCount = Object.keys(resolved).length;

  // ── Slice 3 · transversal interaction baseline (Smell-1 · decision 66 arc #0) ──
  // The decision-45 cross-component constants (pressScale · disabledOpacity),
  // read from the --nuri-interaction-* primitive family and emitted to their
  // OWN transversal artifact at build/interaction.ts. The RN factory's theme
  // reads this directly — it no longer reaches into a per-component file for a
  // non-component value (resolves the R1 "no transversal interaction artifact"
  // finding). NOT a runtime/TokenPath set; the values are context-invariant.
  const interaction = buildInteraction(primitiveMap);
  await writeFile(INTERACTION_OUT, emitInteractionTs(interaction), 'utf8');

  // ── Slice 4 · per-component `@layer tokens` walk (decision 34 · N+6.0.3) ──
  // Walk each component's CSS `@layer tokens` block and resolve each
  // declaration per the SET_POLICY. The per-component FILE emission is
  // RETIRED (Smell-1 · decision 66 arc #0 · build/components/ deleted): the
  // files were read only by the now-retired `button-matrix` mirror (M4), and
  // the lone live value moved to build/interaction.ts above. The walk STAYS so
  // the TokenPath coverage is still reported and the resolver stays exercised;
  // it is INDEPENDENT of the TokenPath union below, which derives from
  // classifiedGroups (the semantic cascade · Slice 5), not from this walk.
  const componentReports = [];
  for (const componentName of COMPONENTS) {
    const componentCssPath = resolve(
      COMPONENTS_DIR, componentName, `${componentName}.css`,
    );
    const componentCSS = await readFile(componentCssPath, 'utf8');
    const componentPrefix = `--nuri-${componentName}-`;
    const declarations = readComponentTokens(componentCSS, componentPrefix);

    // Empty `@layer tokens` case (decision 37 · N+6.2 layout primitives;
    // decision 38 · N+6.3 visual atoms like Icon; 'palette' · N+19 B2b): the
    // component dispatches semantic vocabulary by prop and aliases no
    // component token, so it contributes no TokenPath.
    if (declarations.length === 0) {
      componentReports.push({ componentName, declCount: 0, referencedPaths: new Set() });
      continue;
    }

    const { referencedPaths } = emitComponentTs(
      componentName, declarations,
      { primitives: primitiveMap, classifiedGroups },
    );
    componentReports.push({ componentName, declCount: declarations.length, referencedPaths });
  }

  // ── Slice 5 · TokenPath union emit (N+6.0.3 · decision 34) ────
  // Derived from every runtime-set leaf in classifiedGroups; same
  // pass that emitted tokens.ts walks the same groups so the union
  // and the runtime namespace stay in sync mechanically.
  const tokenPathsSource = emitTokenPathsTs(classifiedGroups);
  await writeFile(TOKEN_PATHS_OUT, tokenPathsSource, 'utf8');

  // ── Slice 6 · typed icon registry emit (N+6.8 · decision 48) ──
  // Emit build/icons.ts from lib/components/icon/icons.js — the SSOT
  // the web inlines directly. ONE registry, TWO readers: web inline +
  // RN react-native-svg SvgXml. Not a token classifier — a verbatim
  // typed mirror, sync-guarded by the test.
  const iconsSource = emitIconsTs(ICONS);
  await writeFile(ICONS_OUT, iconsSource, 'utf8');
  const iconNameCount = Object.keys(ICONS).length;

  // ── Slice 7 · per-component descriptor emit (N+19 · decision 65 · §9 step 1 · decision 69) ──
  // Under build/descriptors/ (a separate dir · independent of every other slice).
  // §9 step 1 INVERTED the source: each descriptor is HAND-AUTHORED at
  // pipeline/descriptors/<name>.ts (the SoT · decision 2 reversed for the layer ·
  // decision 69) and emitted FROM there as a verbatim passthrough — the DATA is
  // byte-identical, only the provenance header changes. No CSS is read here;
  // derivation is now the parity oracle (Guard D), not the producer. The frozen
  // schema (build/descriptors/schema.ts) is likewise the hand-maintained source
  // emitted verbatim (its tokens-import rewritten · the descriptors' `./schema`
  // import needs no rewrite — it resolves in both locations).
  await mkdir(DESCRIPTORS_OUT, { recursive: true });
  const schemaSource = await readFile(SCHEMA_SRC, 'utf8');
  await writeFile(resolve(DESCRIPTORS_OUT, 'schema.ts'), emitSchemaTs(schemaSource), 'utf8');
  const descriptorReports = [];
  for (const spec of DESCRIPTOR_COMPONENTS) {
    const source = await readFile(resolve(DESCRIPTORS_SRC, `${spec.name}.ts`), 'utf8');
    const out = resolve(DESCRIPTORS_OUT, `${spec.name}.ts`);
    await writeFile(out, emitDescriptorTsFromSource(spec, source), 'utf8');
    // Browser-ESM twin (decision 67) — the authored .ts type-stripped (the runtime
    // web factory imports it with no build step · zero-build). Gated to
    // BROWSER_DESCRIPTOR_COMPONENTS. Additive (decision 35).
    let browser = false;
    if (BROWSER_DESCRIPTOR_COMPONENTS.includes(spec.name)) {
      await writeFile(resolve(DESCRIPTORS_OUT, `${spec.name}.js`), emitDescriptorJsFromSource(spec, source), 'utf8');
      browser = true;
    }
    descriptorReports.push({ name: spec.name, out, browser });
  }

  // ── Slice 8 · palette mapping emit (N+19 B2b · decision 65.3 §6) ──
  // ADDITIVE at build/palette.ts: the {variant | chrome} → {bg, fg,
  // fgMuted, pressedBg} table as TokenPath data, emitted ONCE in the
  // baseline (decision 65.2). derivePalette asserts every contract
  // cell against the CSS SoT (palette.css + the recipe CSS) before
  // emitting — a contradiction fails the build (decision 48).
  const paletteSources = {
    button:     await readFile(resolve(COMPONENTS_DIR, 'button/button.css'), 'utf8'),
    iconAvatar: await readFile(resolve(COMPONENTS_DIR, 'icon-avatar/icon-avatar.css'), 'utf8'),
    topbar:     await readFile(resolve(COMPONENTS_DIR, 'topbar/topbar.css'), 'utf8'),
    typography: await readFile(resolve(COMPONENTS_DIR, 'typography/typography.css'), 'utf8'),
    palette:    await readFile(resolve(COMPONENTS_DIR, 'palette/palette.css'), 'utf8'),
  };
  const paletteCells = derivePalette(paletteSources, { classifiedGroups });
  await writeFile(PALETTE_OUT, emitPaletteTs(paletteCells), 'utf8');
  const paletteRowCount =
    Object.keys(paletteCells.variant).length + Object.keys(paletteCells.chrome).length;

  // ── Slice 9 · component doc page emit (N+22 · decision 66 arc #1 · decision 69) ──
  // Render the descriptor as a just-the-docs Markdown page — the generation thesis
  // applied to docs (north-star move 3). The doc IR is sourced from the AUTHORED
  // descriptor (the SoT · decision 69 · §9 step 1), NOT re-derived from CSS: we
  // import the browser-ESM twin emitted in Slice 7 (node 20 cannot import the .ts
  // SoT directly) and build the IR via docIrFromDescriptor. Still READ-ONLY (we
  // EMIT docs, we generate NO CSS — CSS generation is B2). Additive committed build
  // output (decision 35 · build/docs/<source>.md · re-emits byte-identical).
  // The <nuri-demo> STORY is authored in website/_includes (decision 57.2),
  // the page only carries an `## Example` include slot. The value-bearing inputs
  // (the scale maps that DOUBLE as the leaf-validation sets · the type composite ·
  // the default-scope colour resolver) are built from the same live build data
  // tokens.ts/palette.ts emit (decision 48 · one source, two readers) — the
  // SINGLE builder Guard G also calls, so the page re-emits byte-identical (N+23).
  const { tokens: docTokens, colors: docColors } = buildDocTokenInputs(
    classifiedGroups, resolved, typeScale,
  );
  await mkdir(DOCS_OUT, { recursive: true });
  // Slice 9 sources each doc IR from the component's browser-ESM twin (decision 69),
  // so every DOC_COMPONENTS entry MUST also emit one. Assert the subset explicitly —
  // fail loud here rather than on a cryptic import ENOENT below.
  const missingTwin = DOC_COMPONENTS.filter((n) => !BROWSER_DESCRIPTOR_COMPONENTS.includes(n));
  if (missingTwin.length) {
    throw new Error(
      `[tokens-parser] Slice 9 reads the descriptor SoT via its browser-ESM twin, but ` +
      `DOC_COMPONENTS has no twin for: ${missingTwin.join(', ')}. Add them to ` +
      `BROWSER_DESCRIPTOR_COMPONENTS (DOC_COMPONENTS ⊆ BROWSER_DESCRIPTOR_COMPONENTS).`,
    );
  }
  const docReports = [];
  for (const spec of DESCRIPTOR_COMPONENTS) {
    if (!DOC_COMPONENTS.includes(spec.name)) continue;
    // DOC_COMPONENTS ⊆ BROWSER_DESCRIPTOR_COMPONENTS (asserted above), so the twin exists.
    const twin = pathToFileURL(resolve(DESCRIPTORS_OUT, `${spec.name}.js`)).href;
    const descriptor = (await import(twin))[exportNameFor(spec.name)];
    const ir = docIrFromDescriptor(spec, descriptor);
    const out = resolve(DOCS_OUT, `${spec.source}.md`);
    await writeFile(
      out, emitDocPage(ir, { palette: paletteCells, tokens: docTokens, colors: docColors }), 'utf8',
    );
    docReports.push({ source: spec.source, axes: Object.keys(ir.axes).length, out });
  }

  console.log(
    `[tokens-parser] wrote ${jsonCount} colour primitives → ${JSON_OUT}\n` +
    `[tokens-parser] wrote ${semanticCount} semantic tokens × ${ACCENTS.length} accents × ${THEMES.length} themes → ${TS_OUT}\n` +
    `[tokens-parser] wrote type scale (${TYPE_SIZES.length} steps × {regular, em}) → ${TS_OUT}\n` +
    `[tokens-parser] wrote interaction baseline (${Object.keys(INTERACTION_PRIMITIVES).length} constants · transversal) → ${INTERACTION_OUT}\n` +
    componentReports.map((r) =>
      r.declCount === 0
        ? `[tokens-parser] walked component '${r.componentName}' (0 decls · empty @layer tokens)`
        : `[tokens-parser] walked component '${r.componentName}' (${r.declCount} decls, ${r.referencedPaths.size} TokenPath refs · no file · build/components retired)`,
    ).join('\n') +
    `\n[tokens-parser] wrote TokenPath union → ${TOKEN_PATHS_OUT}` +
    `\n[tokens-parser] wrote icon registry (${iconNameCount} names × ${ICON_WEIGHTS.length} weights) → ${ICONS_OUT}` +
    `\n[tokens-parser] wrote descriptor schema → ${resolve(DESCRIPTORS_OUT, 'schema.ts')}` +
    descriptorReports.map((r) =>
      `\n[tokens-parser] wrote descriptor '${r.name}' (authored SoT${r.browser ? ' + browser ESM' : ''}) → ${r.out}`,
    ).join('') +
    `\n[tokens-parser] wrote palette mapping (${paletteRowCount} rows · CSS-asserted) → ${PALETTE_OUT}` +
    docReports.map((r) =>
      `\n[tokens-parser] wrote doc page '${r.source}' (${r.axes} ${r.axes === 1 ? 'axis' : 'axes'} · generated) → ${r.out}`,
    ).join(''),
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
