/* ──────────────────────────────────────────────────────────────
 * NURI · TOKENS PARSER (Node) · ORCHESTRATOR
 * Reads styles/tokens-primitive.css → emits build/tokens.json (DTCG-
 * nested, colour primitive scope) AND walks styles/tokens-semantic.css
 * to emit build/tokens.ts (per-(accent × theme) resolved literals for
 * the migration agent + RN runtime).
 *
 * Lives at pipeline/tokens-parser.js — pipeline sources hand-
 * maintained, build/ outputs are 100% generated by this orchestrator
 * (decision 35 · N+6.0.4). Primitive logic lives in parsers/primitive.js;
 * semantic-cascade resolution + tokens.ts emitter live in
 * parsers/semantic.js; the per-component `@layer` walk + TokenPath union
 * live in parsers/components.js (the per-component FILE emit was retired
 * at Smell-1 · decision 66 arc #0). This file is the orchestrator and the
 * backwards-compatible re-export point for the existing primitive
 * round-trip tests.
 *
 * Companion to the browser parser at lib/docs/tokens.js — same shape,
 * different read environment (postcss vs document.styleSheets).
 *
 * See skills/pipeline-dtcg-export.md and docs/RISKS.md R2 for the
 * workstream context.
 * ────────────────────────────────────────────────────────────── */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
} from './parsers/primitive.js';

import {
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
} from './parsers/semantic.js';

import {
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
} from './parsers/components.js';

import { emitIconsTs, ICON_WEIGHTS } from './parsers/icons.js';

import { buildTypeScale, emitTypeTs, TYPE_SIZES } from './parsers/type.js';

import {
  buildInteraction,
  emitInteractionTs,
  INTERACTION_PRIMITIVES,
} from './parsers/interaction.js';

import {
  DESCRIPTOR_COMPONENTS,
  deriveDescriptor,
  emitDescriptorTs,
  emitSchemaTs,
} from './parsers/descriptors.js';

import {
  PALETTE_CONTRACT,
  derivePalette,
  emitPaletteTs,
} from './parsers/palette.js';

import { ICONS } from '../lib/components/icon/icons.js';

// Re-export so existing imports (and the primitive round-trip tests)
// keep working unchanged across the split.
export {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
  emitIconsTs,
  ICON_WEIGHTS,
  buildTypeScale,
  emitTypeTs,
  TYPE_SIZES,
  buildInteraction,
  emitInteractionTs,
  INTERACTION_PRIMITIVES,
  DESCRIPTOR_COMPONENTS,
  deriveDescriptor,
  emitDescriptorTs,
  emitSchemaTs,
  PALETTE_CONTRACT,
  derivePalette,
  emitPaletteTs,
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

const PRIMITIVE_CSS    = resolve(REPO_ROOT, 'styles/tokens-primitive.css');
const SEMANTIC_CSS     = resolve(REPO_ROOT, 'styles/tokens-semantic.css');
const COMPONENTS_DIR   = resolve(REPO_ROOT, 'lib/components');
const PAGES_DIR        = resolve(REPO_ROOT, 'pages/components');
const JSON_OUT         = resolve(REPO_ROOT, 'build/tokens.json');
const TS_OUT           = resolve(REPO_ROOT, 'build/tokens.ts');
const INTERACTION_OUT  = resolve(REPO_ROOT, 'build/interaction.ts');
const TOKEN_PATHS_OUT  = resolve(REPO_ROOT, 'build/token-paths.ts');
const ICONS_OUT        = resolve(REPO_ROOT, 'build/icons.ts');
const DESCRIPTORS_OUT  = resolve(REPO_ROOT, 'build/descriptors');
const SCHEMA_SRC       = resolve(REPO_ROOT, 'pipeline/descriptors/schema.ts');
const PALETTE_OUT      = resolve(REPO_ROOT, 'build/palette.ts');

// Per-component `@layer tokens` WALK list (decision 34 · N+6.0.3 ·
// extended at decisions 37 / 38 / 44). The per-component FILE emission
// (build/components/<name>.ts) is RETIRED — Smell-1 · decision 66
// arc #0: those files were consumed only by the now-retired
// `button-matrix` mirror (M4), and the lone live value — the
// decision-45 interaction baseline — moved to its own transversal emit
// at build/interaction.ts. The walk STAYS: it computes the per-component
// TokenPath coverage for the build log and keeps the resolver
// (readComponentTokens · resolveComponentValue) exercised end-to-end.
//
// 'tabs' (decision 43) matches the exact `--nuri-tabs-` prefix (the
// `--nuri-tab-` option tokens stay web-CSS-only). Layout primitives
// (decision 37) · visual atoms like Icon (decision 38) · 'palette'
// (N+19 B2b · decision 65.3 §6) carry an empty `@layer tokens` and
// contribute no paths; 'palette' emits its MAPPING through the dedicated
// Slice 7 below (build/palette.ts · pipeline/parsers/palette.js).
const COMPONENTS = ['button', 'stack', 'box', 'screen', 'scroll', 'spacer', 'icon', 'icon-button', 'icon-avatar', 'list', 'list-item', 'list-interactive-item', 'nav-item', 'separator', 'switch', 'tab-bar', 'tabs', 'topbar', 'typography', 'typography-stack', 'palette'];

// Parse the orchestrator's CLI flag `--neutral=<scale>` from argv
// (decision 31). Default = DEFAULT_NEUTRAL. validateNeutral throws on
// unknown scales; no fallback, no env var — operator picked CLI-only
// in the post-N+5.7 thread. Manual parsing avoids a dependency for
// one flag.
export function parseArgs(argv) {
  const arg = argv.find((a) => a.startsWith('--neutral='));
  if (!arg) return DEFAULT_NEUTRAL;
  return validateNeutral(arg.slice('--neutral='.length));
}

async function main() {
  const neutral = parseArgs(process.argv);
  console.log(`[tokens-parser] data-neutral=${neutral}`);

  const primitiveCSS = await readFile(PRIMITIVE_CSS, 'utf8');
  const semanticCSS  = await readFile(SEMANTIC_CSS,  'utf8');

  // ── Slice 1 · colour-primitive DTCG JSON (N+3.5) ──────────────
  const primitives = await readPrimitives(primitiveCSS);
  const tree = buildDtcg(primitives, (v) => v.startsWith('--nuri-color-'));
  await mkdir(dirname(JSON_OUT), { recursive: true });
  await writeFile(JSON_OUT, JSON.stringify(tree, null, 2) + '\n', 'utf8');
  const jsonCount = countLeaves(tree);

  // ── Slice 2 · semantic-cascade → tokens.ts literals (N+5) ─────
  const primitiveMap = buildPrimitiveMap(primitiveCSS, neutral);
  const semanticRules = readSemanticRules(semanticCSS);
  const resolved = resolveSemanticCrossProduct(semanticRules, primitiveMap);
  // The `type` namespace joins tokens.ts as a directly-accessed,
  // context-invariant composite emitted from the --nuri-type-*
  // primitives (decision 54 · the icon model · one source, two
  // readers). It is appended after the cascade-resolved runtime
  // groups; it is NOT a runtime/TokenPath set.
  const typeScale = buildTypeScale(primitiveMap);
  const tsSource = emitTokensTs(resolved, semanticRules) + '\n' + emitTypeTs(typeScale);
  await writeFile(TS_OUT, tsSource, 'utf8');
  const classifiedGroups = classifyAll(semanticRules);
  const semanticCount = Object.keys(resolved).length;

  // ── Slice 3 · transversal interaction baseline (Smell-1 · decision 66 arc #0) ──
  // The decision-45 cross-component constants (pressScale · disabledOpacity),
  // read from the --nuri-interaction-* primitive family and emitted to their
  // OWN transversal artifact at build/interaction.ts. The RN factory's theme
  // reads this directly — it no longer reaches into a per-component file for a
  // non-component value (resolves the R1 "no transversal interaction artifact"
  // finding). NOT a runtime/TokenPath set; the values are context-invariant.
  const interaction = buildInteraction(primitiveMap);
  await writeFile(INTERACTION_OUT, emitInteractionTs(interaction), 'utf8');

  // ── Slice 4 · per-component `@layer tokens` walk (decision 34 · N+6.0.3) ──
  // Walk each component's CSS `@layer tokens` block and resolve each
  // declaration per the SET_POLICY. The per-component FILE emission is
  // RETIRED (Smell-1 · decision 66 arc #0 · build/components/ deleted): the
  // files were read only by the now-retired `button-matrix` mirror (M4), and
  // the lone live value moved to build/interaction.ts above. The walk STAYS so
  // the TokenPath coverage is still reported and the resolver stays exercised;
  // it is INDEPENDENT of the TokenPath union below, which derives from
  // classifiedGroups (the semantic cascade · Slice 5), not from this walk.
  const componentReports = [];
  for (const componentName of COMPONENTS) {
    const componentCssPath = resolve(
      COMPONENTS_DIR, componentName, `${componentName}.css`,
    );
    const componentCSS = await readFile(componentCssPath, 'utf8');
    const componentPrefix = `--nuri-${componentName}-`;
    const declarations = readComponentTokens(componentCSS, componentPrefix);

    // Empty `@layer tokens` case (decision 37 · N+6.2 layout primitives;
    // decision 38 · N+6.3 visual atoms like Icon; 'palette' · N+19 B2b): the
    // component dispatches semantic vocabulary by prop and aliases no
    // component token, so it contributes no TokenPath.
    if (declarations.length === 0) {
      componentReports.push({ componentName, declCount: 0, referencedPaths: new Set() });
      continue;
    }

    const { referencedPaths } = emitComponentTs(
      componentName, declarations,
      { primitives: primitiveMap, classifiedGroups },
    );
    componentReports.push({ componentName, declCount: declarations.length, referencedPaths });
  }

  // ── Slice 5 · TokenPath union emit (N+6.0.3 · decision 34) ────
  // Derived from every runtime-set leaf in classifiedGroups; same
  // pass that emitted tokens.ts walks the same groups so the union
  // and the runtime namespace stay in sync mechanically.
  const tokenPathsSource = emitTokenPathsTs(classifiedGroups);
  await writeFile(TOKEN_PATHS_OUT, tokenPathsSource, 'utf8');

  // ── Slice 6 · typed icon registry emit (N+6.8 · decision 48) ──
  // Emit build/icons.ts from lib/components/icon/icons.js — the SSOT
  // the web inlines directly. ONE registry, TWO readers: web inline +
  // RN react-native-svg SvgXml. Not a token classifier — a verbatim
  // typed mirror, sync-guarded by the test.
  const iconsSource = emitIconsTs(ICONS);
  await writeFile(ICONS_OUT, iconsSource, 'utf8');
  const iconNameCount = Object.keys(ICONS).length;

  // ── Slice 7 · per-component descriptor emit (N+19 · decision 65 · 65.2) ──
  // Under build/descriptors/ (a separate dir · independent of every other
  // slice · re-emits byte-identical). One descriptor per spike-validated
  // component, read from BOTH sources: the @layer CSS
  // (mapping · the 65.1 bootstrap) + the page data-part anatomy (structure ·
  // decision 24.1). The frozen schema (build/descriptors/schema.ts) is the
  // hand-maintained pipeline source emitted verbatim (tokens-import rewritten).
  await mkdir(DESCRIPTORS_OUT, { recursive: true });
  const schemaSource = await readFile(SCHEMA_SRC, 'utf8');
  await writeFile(resolve(DESCRIPTORS_OUT, 'schema.ts'), emitSchemaTs(schemaSource), 'utf8');
  const descriptorReports = [];
  for (const spec of DESCRIPTOR_COMPONENTS) {
    const descriptorCSS = await readFile(
      resolve(COMPONENTS_DIR, spec.source, `${spec.source}.css`), 'utf8',
    );
    const descriptorHTML = await readFile(
      resolve(PAGES_DIR, `${spec.source}.html`), 'utf8',
    );
    const ir = deriveDescriptor(spec, { css: descriptorCSS, html: descriptorHTML });
    const out = resolve(DESCRIPTORS_OUT, `${spec.name}.ts`);
    await writeFile(out, emitDescriptorTs(ir), 'utf8');
    descriptorReports.push({ name: spec.name, axes: Object.keys(ir.axes).length, out });
  }

  // ── Slice 8 · palette mapping emit (N+19 B2b · decision 65.3 §6) ──
  // ADDITIVE at build/palette.ts: the {variant | chrome} → {bg, fg,
  // fgMuted, pressedBg} table as TokenPath data, emitted ONCE in the
  // baseline (decision 65.2). derivePalette asserts every contract
  // cell against the CSS SoT (palette.css + the recipe CSS) before
  // emitting — a contradiction fails the build (decision 48).
  const paletteSources = {
    button:     await readFile(resolve(COMPONENTS_DIR, 'button/button.css'), 'utf8'),
    iconAvatar: await readFile(resolve(COMPONENTS_DIR, 'icon-avatar/icon-avatar.css'), 'utf8'),
    topbar:     await readFile(resolve(COMPONENTS_DIR, 'topbar/topbar.css'), 'utf8'),
    typography: await readFile(resolve(COMPONENTS_DIR, 'typography/typography.css'), 'utf8'),
    palette:    await readFile(resolve(COMPONENTS_DIR, 'palette/palette.css'), 'utf8'),
  };
  const paletteCells = derivePalette(paletteSources, { classifiedGroups });
  await writeFile(PALETTE_OUT, emitPaletteTs(paletteCells), 'utf8');
  const paletteRowCount =
    Object.keys(paletteCells.variant).length + Object.keys(paletteCells.chrome).length;

  console.log(
    `[tokens-parser] wrote ${jsonCount} colour primitives → ${JSON_OUT}\n` +
    `[tokens-parser] wrote ${semanticCount} semantic tokens × ${ACCENTS.length} accents × ${THEMES.length} themes → ${TS_OUT}\n` +
    `[tokens-parser] wrote type scale (${TYPE_SIZES.length} steps × {regular, em}) → ${TS_OUT}\n` +
    `[tokens-parser] wrote interaction baseline (${Object.keys(INTERACTION_PRIMITIVES).length} constants · transversal) → ${INTERACTION_OUT}\n` +
    componentReports.map((r) =>
      r.declCount === 0
        ? `[tokens-parser] walked component '${r.componentName}' (0 decls · empty @layer tokens)`
        : `[tokens-parser] walked component '${r.componentName}' (${r.declCount} decls, ${r.referencedPaths.size} TokenPath refs · no file · build/components retired)`,
    ).join('\n') +
    `\n[tokens-parser] wrote TokenPath union → ${TOKEN_PATHS_OUT}` +
    `\n[tokens-parser] wrote icon registry (${iconNameCount} names × ${ICON_WEIGHTS.length} weights) → ${ICONS_OUT}` +
    `\n[tokens-parser] wrote descriptor schema → ${resolve(DESCRIPTORS_OUT, 'schema.ts')}` +
    descriptorReports.map((r) =>
      `\n[tokens-parser] wrote descriptor '${r.name}' (${r.axes} ${r.axes === 1 ? 'axis' : 'axes'}) → ${r.out}`,
    ).join('') +
    `\n[tokens-parser] wrote palette mapping (${paletteRowCount} rows · CSS-asserted) → ${PALETTE_OUT}`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
