/* ──────────────────────────────────────────────────────────────
 * NURI · TOKENS PARSER (Node) · ORCHESTRATOR
 * Reads styles/tokens-primitive.css → emits build/tokens.json (DTCG-
 * nested, colour primitive scope) AND walks styles/tokens-semantic.css
 * to emit build/tokens.ts (per-(accent × theme) resolved literals for
 * the migration agent + RN runtime).
 *
 * Lives at pipeline/tokens-parser.js — pipeline sources hand-
 * maintained, build/ outputs are 100% generated by this orchestrator
 * (decision 35 · N+6.0.4). Primitive logic lives in parsers/primitive.js;
 * semantic-cascade resolution + tokens.ts emitter live in
 * parsers/semantic.js; per-component emit + TokenPath union live in
 * parsers/components.js. This file is the orchestrator and the
 * backwards-compatible re-export point for the existing primitive
 * round-trip tests.
 *
 * Companion to the browser parser at lib/docs/tokens.js — same shape,
 * different read environment (postcss vs document.styleSheets).
 *
 * See skills/pipeline-dtcg-export.md and docs/RISKS.md R2 for the
 * workstream context.
 * ────────────────────────────────────────────────────────────── */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
} from './parsers/primitive.js';

import {
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
} from './parsers/semantic.js';

import {
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
} from './parsers/components.js';

import { emitIconsTs, ICON_WEIGHTS } from './parsers/icons.js';

import { buildTypeScale, emitTypeTs, TYPE_SIZES } from './parsers/type.js';

import { ICONS } from '../lib/components/icon/icons.js';

// Re-export so existing imports (and the primitive round-trip tests)
// keep working unchanged across the split.
export {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
  emitIconsTs,
  ICON_WEIGHTS,
  buildTypeScale,
  emitTypeTs,
  TYPE_SIZES,
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');

const PRIMITIVE_CSS    = resolve(REPO_ROOT, 'styles/tokens-primitive.css');
const SEMANTIC_CSS     = resolve(REPO_ROOT, 'styles/tokens-semantic.css');
const COMPONENTS_DIR   = resolve(REPO_ROOT, 'lib/components');
const JSON_OUT         = resolve(REPO_ROOT, 'build/tokens.json');
const TS_OUT           = resolve(REPO_ROOT, 'build/tokens.ts');
const COMPONENTS_OUT   = resolve(REPO_ROOT, 'build/components');
const TOKEN_PATHS_OUT  = resolve(REPO_ROOT, 'build/token-paths.ts');
const ICONS_OUT        = resolve(REPO_ROOT, 'build/icons.ts');

// Per-component emit list (decision 34 · N+6.0.3 · extended at
// decision 37 · N+6.2 · decision 38 · N+6.3 · decision 44 · N+6.5).
// Walker visits every entry; the emitter detects the "empty @layer
// tokens" case (layout primitives per decision 37; visual atoms like
// Icon per decision 38) and gracefully skips writing a file.
//
// Note · 'tabs' (decision 43) is the compound's single registry
// entry. The emitter matches the exact `--nuri-tabs-` prefix, so the
// container tokens emit to build/components/tabs.ts while the
// `--nuri-tab-` option tokens stay web-CSS-only by design (no
// separate 'tab' entry).
const COMPONENTS = ['button', 'stack', 'box', 'screen', 'scroll', 'spacer', 'icon', 'icon-button', 'icon-avatar', 'list', 'list-item', 'list-interactive-item', 'nav-item', 'separator', 'switch', 'tab-bar', 'tabs', 'topbar', 'typography', 'typography-stack'];

// Parse the orchestrator's CLI flag `--neutral=<scale>` from argv
// (decision 31). Default = DEFAULT_NEUTRAL. validateNeutral throws on
// unknown scales; no fallback, no env var — operator picked CLI-only
// in the post-N+5.7 thread. Manual parsing avoids a dependency for
// one flag.
export function parseArgs(argv) {
  const arg = argv.find((a) => a.startsWith('--neutral='));
  if (!arg) return DEFAULT_NEUTRAL;
  return validateNeutral(arg.slice('--neutral='.length));
}

async function main() {
  const neutral = parseArgs(process.argv);
  console.log(`[tokens-parser] data-neutral=${neutral}`);

  const primitiveCSS = await readFile(PRIMITIVE_CSS, 'utf8');
  const semanticCSS  = await readFile(SEMANTIC_CSS,  'utf8');

  // ── Slice 1 · colour-primitive DTCG JSON (N+3.5) ──────────────
  const primitives = await readPrimitives(primitiveCSS);
  const tree = buildDtcg(primitives, (v) => v.startsWith('--nuri-color-'));
  await mkdir(dirname(JSON_OUT), { recursive: true });
  await writeFile(JSON_OUT, JSON.stringify(tree, null, 2) + '\n', 'utf8');
  const jsonCount = countLeaves(tree);

  // ── Slice 2 · semantic-cascade → tokens.ts literals (N+5) ─────
  const primitiveMap = buildPrimitiveMap(primitiveCSS, neutral);
  const semanticRules = readSemanticRules(semanticCSS);
  const resolved = resolveSemanticCrossProduct(semanticRules, primitiveMap);
  // The `type` namespace joins tokens.ts as a directly-accessed,
  // context-invariant composite emitted from the --nuri-type-*
  // primitives (decision 54 · the icon model · one source, two
  // readers). It is appended after the cascade-resolved runtime
  // groups; it is NOT a runtime/TokenPath set.
  const typeScale = buildTypeScale(primitiveMap);
  const tsSource = emitTokensTs(resolved, semanticRules) + '\n' + emitTypeTs(typeScale);
  await writeFile(TS_OUT, tsSource, 'utf8');
  const classifiedGroups = classifyAll(semanticRules);
  const semanticCount = Object.keys(resolved).length;

  // ── Slice 3 · per-component emit (N+6.0.3 · decision 34) ──────
  // Walk each component's CSS `@layer tokens` block, resolve each
  // declaration per the SET_POLICY, and emit
  // build/components/<name>.ts. Aggregate the referenced TokenPath
  // strings so the union emit below can audit coverage.
  await mkdir(COMPONENTS_OUT, { recursive: true });
  const componentReports = [];
  for (const componentName of COMPONENTS) {
    const componentCssPath = resolve(
      COMPONENTS_DIR, componentName, `${componentName}.css`,
    );
    const componentCSS = await readFile(componentCssPath, 'utf8');
    const componentPrefix = `--nuri-${componentName}-`;
    const declarations = readComponentTokens(componentCSS, componentPrefix);

    // Empty `@layer tokens` case (decision 37 · N+6.2 layout
    // primitives; decision 38 · N+6.3 visual atoms like Icon). The
    // component parametrizes semantic vocabulary via prop (attribute-
    // dispatch in @layer rules) and has no component-token aliasing —
    // no per-component file ships. The walker still visits so
    // `COMPONENTS` stays the single registry; the emit step is the
    // graceful no-op.
    if (declarations.length === 0) {
      componentReports.push({
        componentName, declCount: 0, referencedPaths: new Set(),
        out: null, skipped: true,
      });
      continue;
    }

    const { source, referencedPaths } = emitComponentTs(
      componentName, declarations,
      { primitives: primitiveMap, classifiedGroups },
    );
    const out = resolve(COMPONENTS_OUT, `${componentName}.ts`);
    await writeFile(out, source, 'utf8');
    componentReports.push({ componentName, declCount: declarations.length, referencedPaths, out });
  }

  // ── Slice 4 · TokenPath union emit (N+6.0.3 · decision 34) ────
  // Derived from every runtime-set leaf in classifiedGroups; same
  // pass that emitted tokens.ts walks the same groups so the union
  // and the runtime namespace stay in sync mechanically.
  const tokenPathsSource = emitTokenPathsTs(classifiedGroups);
  await writeFile(TOKEN_PATHS_OUT, tokenPathsSource, 'utf8');

  // ── Slice 5 · typed icon registry emit (N+6.8 · decision 48) ──
  // Emit build/icons.ts from lib/components/icon/icons.js — the SSOT
  // the web inlines directly. ONE registry, TWO readers: web inline +
  // RN react-native-svg SvgXml. Not a token classifier — a verbatim
  // typed mirror, sync-guarded by the test.
  const iconsSource = emitIconsTs(ICONS);
  await writeFile(ICONS_OUT, iconsSource, 'utf8');
  const iconNameCount = Object.keys(ICONS).length;

  console.log(
    `[tokens-parser] wrote ${jsonCount} colour primitives → ${JSON_OUT}\n` +
    `[tokens-parser] wrote ${semanticCount} semantic tokens × ${ACCENTS.length} accents × ${THEMES.length} themes → ${TS_OUT}\n` +
    `[tokens-parser] wrote type scale (${TYPE_SIZES.length} steps × {regular, em}) → ${TS_OUT}\n` +
    componentReports.map((r) =>
      r.skipped
        ? `[tokens-parser] wrote component '${r.componentName}' (0 decls · empty @layer tokens · no per-component file emitted)`
        : `[tokens-parser] wrote component '${r.componentName}' (${r.declCount} decls, ${r.referencedPaths.size} TokenPath refs) → ${r.out}`,
    ).join('\n') +
    `\n[tokens-parser] wrote TokenPath union → ${TOKEN_PATHS_OUT}` +
    `\n[tokens-parser] wrote icon registry (${iconNameCount} names × ${ICON_WEIGHTS.length} weights) → ${ICONS_OUT}`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
