/* ──────────────────────────────────────────────────────────────
 * NURI · TOKENS PARSER (Node) · ORCHESTRATOR
 * Reads styles/tokens-primitive.css → emits build/tokens.json (DTCG-
 * nested, colour primitive scope) AND walks styles/tokens-semantic.css
 * to emit build/tokens.ts (per-(accent × theme) resolved literals for
 * the migration agent + RN runtime).
 *
 * Lives at pipeline/tokens-parser.js — pipeline sources hand-
 * maintained, build/ outputs are 100% generated by this orchestrator
 * (decision 35 · N+6.0.4). Primitive logic lives in parsers/primitive.js;
 * semantic-cascade resolution + tokens.ts emitter live in
 * parsers/semantic.js; the per-component `@layer` walk + TokenPath union
 * live in parsers/components.js (the per-component FILE emit was retired
 * at Smell-1 · decision 66 arc #0). This file is the orchestrator and the
 * backwards-compatible re-export point for the existing primitive
 * round-trip tests.
 *
 * Companion to the browser parser at lib/docs/tokens.js — same shape,
 * different read environment (postcss vs document.styleSheets).
 *
 * See skills/pipeline-dtcg-export.md and docs/RISKS.md R2 for the
 * workstream context.
 * ────────────────────────────────────────────────────────────── */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
} from './parsers/primitive.js';

import {
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  emitTokenVarsTs,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
} from './parsers/semantic.js';

import {
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
} from './parsers/components.js';

import { readIcons, emitIconsJs, emitIconsTs } from './parsers/icons.js';

import { buildTypeScale, emitTypeTs, TYPE_SIZES } from './parsers/type.js';

import {
  buildInteraction,
  emitInteractionTs,
  INTERACTION_PRIMITIVES,
} from './parsers/interaction.js';

import {
  DESCRIPTOR_COMPONENTS,
  deriveDescriptor,
  emitDescriptorTs,
  emitDescriptorTsFromSource,
  emitDescriptorJsFromSource,
  exportNameFor,
  emitSchemaTs,
} from './parsers/descriptors.js';

import {
  PALETTE_CONTRACT,
  derivePalette,
  emitPaletteTs,
} from './parsers/palette.js';

// (parsers/docs.js · emitDocPage / buildDocTokenInputs · MOVED to @nuri/doc at
// N+42 · the A4 carve · convergence §5. @nuri/spec no longer transforms data → docs.)

import { loadDimensions, flipDimensionCss, stripTypes } from './parsers/dimension-css.js';

import { loadColours, flipColourCss } from './parsers/colour-css.js';

import { loadSemanticColours, flipSemanticCss } from './parsers/semantic-css.js';

import { loadTypography, flipTypeCss } from './parsers/type-css.js';

// The icon registry is GENERATED from the icons/*.svg folder (the SoT · decision 38 ·
// N+51 · convergence phase 4·1). lib/components/icon/icons.js (the web reader) is now a
// build OUTPUT, so the orchestrator no longer imports it — it READS the folder and emits
// both readers (icons.js + build/icons.ts · one registry, two readers · decision 48).

// The namespace-CSS generation (flipNamespaceCss / pipeline/css-preview.js) MOVED to
// @nuri/prototype at N+41 (the A3 carve · convergence §5 · "each library owns the emitter
// for its own surface"). spec's build no longer generates it; prototype regenerates its
// styles/<ns>.css from spec's TS SoTs via `npm run build -w @nuri/prototype`.

// Re-export so existing imports (and the primitive round-trip tests)
// keep working unchanged across the split.
export {
  readPrimitives,
  buildDtcg,
  inferType,
  pathFor,
  countLeaves,
  TYPE_PREFIXES,
  buildPrimitiveMap,
  readSemanticRules,
  resolveSemanticCrossProduct,
  emitTokensTs,
  selectorMatches,
  findWinningDecl,
  resolveValue,
  collectSemanticVars,
  classifySemantic,
  classifyAll,
  emitTokenVarsTs,
  GROUP_NAMES,
  AXIS_REGISTRY,
  ACCENTS,
  THEMES,
  NEUTRAL_SCALES,
  DEFAULT_NEUTRAL,
  validateNeutral,
  SET_POLICY,
  resolveSetPolicy,
  primitiveSetFor,
  readComponentTokens,
  resolveComponentValue,
  emitComponentTs,
  emitTokenPathsTs,
  readIcons,
  emitIconsJs,
  emitIconsTs,
  buildTypeScale,
  emitTypeTs,
  TYPE_SIZES,
  buildInteraction,
  emitInteractionTs,
  INTERACTION_PRIMITIVES,
  DESCRIPTOR_COMPONENTS,
  deriveDescriptor,
  emitDescriptorTs,
  emitDescriptorTsFromSource,
  emitDescriptorJsFromSource,
  exportNameFor,
  emitSchemaTs,
  PALETTE_CONTRACT,
  derivePalette,
  emitPaletteTs,
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '../packages/spec');

const PRIMITIVE_CSS    = resolve(REPO_ROOT, 'styles/tokens-primitive.css');
const SEMANTIC_CSS     = resolve(REPO_ROOT, 'styles/tokens-semantic.css');
const DIMENSIONS_SRC   = resolve(REPO_ROOT, 'pipeline/dimensions.ts');
const COLOURS_SRC      = resolve(REPO_ROOT, 'pipeline/colours.ts');
const TYPOGRAPHY_SRC   = resolve(REPO_ROOT, 'pipeline/typography.ts');
const PALETTE_SURFACE_SRC = resolve(REPO_ROOT, 'pipeline/palette-surface.ts');
const TYPOGRAPHY_AXIS_SRC = resolve(REPO_ROOT, 'pipeline/typography-axis.ts');
const JSON_OUT         = resolve(REPO_ROOT, 'build/tokens.json');
const TS_OUT           = resolve(REPO_ROOT, 'build/tokens.ts');
const INTERACTION_OUT  = resolve(REPO_ROOT, 'build/interaction.ts');
const TOKEN_PATHS_OUT  = resolve(REPO_ROOT, 'build/token-paths.ts');
const TOKEN_VARS_OUT   = resolve(REPO_ROOT, 'build/token-vars.ts');
const ICONS_DIR        = resolve(REPO_ROOT, 'icons');
const ICONS_JS_OUT     = resolve(REPO_ROOT, 'lib/components/icon/icons.js');
const ICONS_OUT        = resolve(REPO_ROOT, 'build/icons.ts');
const DESCRIPTORS_OUT  = resolve(REPO_ROOT, 'build/descriptors');
const DESCRIPTORS_SRC  = resolve(REPO_ROOT, 'pipeline/descriptors');
const SCHEMA_SRC       = resolve(REPO_ROOT, 'pipeline/descriptors/schema.ts');
const PALETTE_OUT      = resolve(REPO_ROOT, 'build/palette.ts');
// (build/docs · DOC_COMPONENTS · MOVED to @nuri/doc at N+42 · the A4 carve. The
// doc-gen left @nuri/spec — @nuri/doc owns the generated Markdown · convergence §5.)

// Component descriptors that ALSO emit a browser-ESM twin (decision 67 · the
// runtime web factory). The .js form lets a browser `import` the descriptor and
// resolve it with NO build step (zero-build · what Nuri IS #3). WIDENED at S4 to
// the FULL DESCRIPTOR_COMPONENTS set — the web factory now de-collapses all
// three frozen descriptors (Button at S3 · icon-avatar + topbar at S4), so each
// has a live consumer (P11 · decision 30 · no speculative emit ahead of one).
const BROWSER_DESCRIPTOR_COMPONENTS = ['composition-button', 'icon-avatar', 'topbar'];

// (Slice 4 · the per-component `@layer tokens` WALK · REMOVED at N+41 · the A3 carve.)
// The walk read each component's lib/components/<name>/<name>.css to report its TokenPath
// coverage in the build LOG. At A3 those CSS files MOVED to @nuri/prototype (the 5 namespace
// CSS → prototype/styles/; the element CSS → prototype/primitives/), so the walk had no files
// left to read. It was always build-output-neutral (the TokenPath union below derives from
// classifiedGroups · Slice 5 · NOT this walk), so removing it leaves build/* byte-identical.
// The resolver it exercised (resolveComponentValue) is covered by tokens-parser.test.js on
// synthetic input (reframed at N+38); the re-export of readComponentTokens / emitComponentTs /
// resolveComponentValue stays (the test API).

// Parse the orchestrator's CLI flag `--neutral=<scale>` from argv
// (decision 31). Default = DEFAULT_NEUTRAL. validateNeutral throws on
// unknown scales; no fallback, no env var — operator picked CLI-only
// in the post-N+5.7 thread. Manual parsing avoids a dependency for
// one flag.
export function parseArgs(argv) {
  const arg = argv.find((a) => a.startsWith('--neutral='));
  if (!arg) return DEFAULT_NEUTRAL;
  return validateNeutral(arg.slice('--neutral='.length));
}

// Load a namespace-axis TS SoT (palette-surface.ts / typography-axis.ts) the
// SPEC-RESIDENT way — the shared one-strip impl (stripTypes · dimension-css.js) +
// a data:-URL import (node 20 cannot import a .ts), exactly as loadDimensions does.
// Deliberately NOT loadSurface/loadAxis from parsers/{palette,typography}-css.js:
// those are the namespace-CSS EMITTERS that leave `spec` at the A3 carve, so reading
// the SoT through them would re-invert the rn→spec DAG this re-source (Slice 8 · §74
// 'Next: final') exists to decouple. A strip regression fails LOUD here.
async function loadAxisSoT(tsPath, exportName) {
  const src = await readFile(tsPath, 'utf8');
  const mod = await import('data:text/javascript,' + encodeURIComponent(stripTypes(src)));
  const value = mod[exportName];
  if (!value || typeof value !== 'object') {
    throw new Error(`[tokens-parser] loadAxisSoT: ${tsPath} export '${exportName}' missing/empty (strip regression?)`);
  }
  return value;
}

async function main() {
  const neutral = parseArgs(process.argv);
  console.log(`[tokens-parser] data-neutral=${neutral}`);

  // ── Slice 0 · the dimension cascade · TS SoT → tokens-*.css (N+31 · decision 70 · the first flip) ──
  // decision 2 reverses for the dimension layer ONLY: the px scale + the
  // space/size/radius semantics are authored in pipeline/dimensions.ts (the
  // SoT) and WRITTEN INTO styles/tokens-{primitive,semantic}.css here, before
  // every downstream slice reads them. The emit is an in-place PASSTHROUGH —
  // only the dimension declarations' values are regenerated; all non-dimension
  // content (colours · the accent×theme cascade · border · type · font · the
  // reserved radius primitives) passes through verbatim (the S1 passthrough-
  // hybrid · no page repointing). Values are unchanged this slice, so every
  // slice below stays byte-identical → build/* byte-identical. Writing into
  // styles/ (a source dir) is the hybrid trade — muddier provenance for zero
  // repointing; the clean physical split is a later L3c-style cleanup.
  const dims = await loadDimensions(DIMENSIONS_SRC);
  await flipDimensionCss({ primitivePath: PRIMITIVE_CSS, semanticPath: SEMANTIC_CSS, dims });
  console.log(
    `[tokens-parser] flipped the dimension cascade from the TS SoT ` +
    `(${Object.keys(dims.px).length} px · ${Object.keys(dims.space).length} space · ` +
    `${Object.keys(dims.size).length} size · ${Object.keys(dims.radius).length} radius) → styles/tokens-*.css`,
  );

  // ── Slice 0 · the colour primitives · TS SoT → tokens-primitive.css (N+32 C1 · decision 70 · the second flip) ──
  // decision 2 reverses for the colour-PRIMITIVE layer (after the dimension layer
  // at N+31): the 7 neutral scales + lilac + the alpha scales are authored in
  // pipeline/colours.ts and WRITTEN INTO styles/tokens-primitive.css here, before
  // every downstream slice reads it. Same in-place PASSTHROUGH as the dimension
  // flip — only the --nuri-color-* declarations are regenerated; the accent×theme
  // cascade (tokens-semantic.css · decision 63) is NOT touched (that is C2). The
  // neutral resolution (--nuri-color-neutral-* → the active scale) is baked from
  // `neutral` (the --neutral flag · default cream) into ONE :root block — the
  // retired runtime [data-neutral] switcher, build-time selection only. At cream
  // the values are unchanged (tokens.ts already resolved cream since decision 31),
  // so build/* stays byte-identical; cream ≠ gray is a web-CSS-only change.
  const colours = await loadColours(COLOURS_SRC);
  await flipColourCss({ primitivePath: PRIMITIVE_CSS, colours, neutral });
  console.log(
    `[tokens-parser] flipped the colour primitives from the TS SoT ` +
    `(${Object.keys(colours.neutralScales).length} neutral scales · lilac · black/white alpha · ` +
    `neutral resolution → ${neutral}) → styles/tokens-primitive.css`,
  );

  // ── Slice 0 · the colour SEMANTIC cascade · TS SoT → tokens-semantic.css (N+32 C2 · decision 70 · the cascade) ──
  // decision 2 reverses for the colour SEMANTIC layer (the second half of the colour
  // vertical · after the primitives at C1) → it is now FULLY reversed for colour. The
  // accent×theme matrix (chrome + accent) is authored in pipeline/colours.ts and the
  // cascade is GENERATED into styles/tokens-semantic.css here (parsers/semantic-css.js):
  // the 8 blocks 1·2·3·4·4b·5·6·6b, INCLUDING the decision-63 #4b/#6b descendant-
  // combinator self-scope that no stock token tool emits. Unlike the dimension /
  // colour-primitive flips this is NOT a byte-identical passthrough — the cascade is
  // regenerated (terser · the resolution matrix moved to the SoT) — but it resolves to
  // the SAME (accent × theme) cross-product, so build/tokens.ts (the RN single-context
  // contract · decisions 27/62/63 · no cascade, no #4b/#6b) stays byte-identical. The
  // generated region replaces a marked span; the file header + the dimension blocks
  // (space/size/radius · Slice 0 above) pass through verbatim.
  const semanticColours = await loadSemanticColours(COLOURS_SRC);
  await flipSemanticCss({ semanticPath: SEMANTIC_CSS, semanticColours });
  console.log(
    `[tokens-parser] flipped the accent×theme cascade from the TS SoT ` +
    `(${Object.keys(semanticColours.chrome).length} chrome × {light,dark} · ` +
    `${Object.keys(semanticColours.accent).length} accent × {neutral,lilac} × {light,dark} · ` +
    `the dec-63 #4b/#6b self-scope) → styles/tokens-semantic.css`,
  );

  // ── Slice 0 · the type composite · TS SoT → tokens-primitive.css (N+52 · decision 78 · the value flip §77 deferred) ──
  // decision 2 reverses for the type COMPOSITE (the value flip §77 deferred to
  // phase 4 · after dimensions N+31 + colour N+32): the six --nuri-type-* step
  // composites are authored in pipeline/typography.ts (a self-contained inline
  // table of text styles · NOT the dimension {ref} shape) and WRITTEN INTO
  // styles/tokens-primitive.css here, before Slice 2 reads it. The --nuri-type-*
  // declarations are regenerated DE-REFERENCED to inline (size → the rem literal ·
  // weight → the resolved literal), so the --nuri-font-size-* / --nuri-font-weight-*
  // PRIMITIVES go back to being a foundational hand-CSS layer (shell.css's concern ·
  // a Phase 4·3 residue · NOT touched here). The resolved VALUES are unchanged, so
  // build/tokens.ts (re-sourced onto this SoT) stays byte-identical; only the
  // --nuri-type-* block's spelling changes (var→inline · computed-equivalent).
  const typeSoT = await loadTypography(TYPOGRAPHY_SRC);
  await flipTypeCss({ primitivePath: PRIMITIVE_CSS, type: typeSoT });
  console.log(
    `[tokens-parser] flipped the type composite from the TS SoT ` +
    `(${Object.keys(typeSoT).length} steps · de-referenced to inline) → styles/tokens-primitive.css`,
  );

  // (The namespace-CSS slice MOVED to @nuri/prototype at N+41 · the A3 carve.) The 5
  // namespace axes (box/stack/palette/interactive/typography) are still GENERATED from the TS
  // SoTs — the dec-74 / dec-2-reversed flip STANDS — but the generator (pipeline/css-preview.js)
  // now lives in @nuri/prototype and writes prototype/styles/<ns>.css via its OWN build
  // (`npm run build -w @nuri/prototype` · convergence §5). It reads spec's SoTs + the generated
  // styles/tokens-semantic.css cross-package (DAG: prototype → spec). spec's build no longer
  // reads or writes the namespace CSS (Slice 8 · derivePalette · reads the TS SoTs directly
  // since N+40), so nothing here depends on it.

  const primitiveCSS = await readFile(PRIMITIVE_CSS, 'utf8');
  const semanticCSS  = await readFile(SEMANTIC_CSS,  'utf8');

  // ── Slice 1 · colour-primitive DTCG JSON (N+3.5) ──────────────
  const primitives = await readPrimitives(primitiveCSS);
  const tree = buildDtcg(primitives, (v) => v.startsWith('--nuri-color-'));
  await mkdir(dirname(JSON_OUT), { recursive: true });
  await writeFile(JSON_OUT, JSON.stringify(tree, null, 2) + '\n', 'utf8');
  const jsonCount = countLeaves(tree);

  // ── Slice 2 · semantic-cascade → tokens.ts literals (N+5) ─────
  const primitiveMap = buildPrimitiveMap(primitiveCSS);
  const semanticRules = readSemanticRules(semanticCSS);
  const resolved = resolveSemanticCrossProduct(semanticRules, primitiveMap);
  // The `type` namespace joins tokens.ts as a directly-accessed,
  // context-invariant composite. RE-SOURCED at N+52 onto the TS SoT
  // (typeSoT · pipeline/typography.ts · decision 78): fontSize/lineHeight/
  // letterSpacing come straight from the inline table; only the weight
  // name resolves against the font-weight primitive in primitiveMap (the
  // one value the scale still references). One source, two readers (the
  // icon model · decision 48). It is appended after the cascade-resolved
  // runtime groups; it is NOT a runtime/TokenPath set.
  const typeScale = buildTypeScale(typeSoT, primitiveMap);
  const tsSource = emitTokensTs(resolved, semanticRules) + '\n' + emitTypeTs(typeScale);
  await writeFile(TS_OUT, tsSource, 'utf8');
  const classifiedGroups = classifyAll(semanticRules);
  const semanticCount = Object.keys(resolved).length;

  // ── Slice 3 · transversal interaction baseline (Smell-1 · decision 66 arc #0) ──
  // The decision-45 cross-component constants (pressScale · disabledOpacity),
  // read from the --nuri-interaction-* primitive family and emitted to their
  // OWN transversal artifact at build/interaction.ts. The RN factory's theme
  // reads this directly — it no longer reaches into a per-component file for a
  // non-component value (resolves the R1 "no transversal interaction artifact"
  // finding). NOT a runtime/TokenPath set; the values are context-invariant.
  const interaction = buildInteraction(primitiveMap);
  await writeFile(INTERACTION_OUT, emitInteractionTs(interaction), 'utf8');

  // (Slice 4 · the per-component `@layer tokens` walk · REMOVED at N+41 · see the note
  // by the former COMPONENTS list above. Its targets moved to @nuri/prototype; it was
  // build-output-neutral. The resolver it exercised is covered by the synthetic
  // tokens-parser.test.js.)

  // ── Slice 5 · TokenPath union emit (N+6.0.3 · decision 34) ────
  // Derived from every runtime-set leaf in classifiedGroups; same
  // pass that emitted tokens.ts walks the same groups so the union
  // and the runtime namespace stay in sync mechanically.
  const tokenPathsSource = emitTokenPathsTs(classifiedGroups);
  await writeFile(TOKEN_PATHS_OUT, tokenPathsSource, 'utf8');

  // ── Slice 5b · semantic colour var registry emit (N+42 · A4 · the @nuri/doc data export) ──
  // build/token-vars.ts: each cascade-varying colour group's leaf → its CSS custom-
  // property name (chrome.bgStrong → --nuri-bg-strong · accent.solid → --nuri-accent-solid),
  // walked from the SAME classifiedGroups Slice 5 reads. @nuri/doc's Token-map / Base
  // swatch reads it to render the LIVE var() chip — the doc-gen left @nuri/spec at A4
  // (convergence §5 · decision 75), so the spec emits this as DATA rather than the doc
  // reaching into the classifier. Additive committed build output (decision 35).
  const tokenVarsSource = emitTokenVarsTs(classifiedGroups);
  await writeFile(TOKEN_VARS_OUT, tokenVarsSource, 'utf8');

  // ── Slice 6 · icon registry emit · the SVG folder is the SoT (N+51 · decision 38/48) ──
  // Read icons/*.svg (the SoT folder · filename = name · one drawing per glyph) → the
  // ICONS registry, then emit BOTH readers from it: the web reader (lib/components/icon/
  // icons.js · zero-build inline) + the typed RN reader (build/icons.ts · SvgXml). ONE
  // registry, TWO readers (decision 48). Both are GENERATED + committed + byte-identical-
  // guarded (decision 35) — adding an icon = dropping a .svg and re-running the build.
  const ICONS = await readIcons(ICONS_DIR);
  await writeFile(ICONS_JS_OUT, emitIconsJs(ICONS), 'utf8');
  await writeFile(ICONS_OUT, emitIconsTs(ICONS), 'utf8');
  const iconNameCount = Object.keys(ICONS).length;

  // ── Slice 7 · per-component descriptor emit (N+19 · decision 65 · §9 step 1 · decision 69) ──
  // Under build/descriptors/ (a separate dir · independent of every other slice).
  // §9 step 1 INVERTED the source: each descriptor is HAND-AUTHORED at
  // pipeline/descriptors/<name>.ts (the SoT · decision 2 reversed for the layer ·
  // decision 69) and emitted FROM there as a verbatim passthrough — the DATA is
  // byte-identical, only the provenance header changes. No CSS is read here;
  // derivation is now the parity oracle (Guard D), not the producer. The frozen
  // schema (build/descriptors/schema.ts) is likewise the hand-maintained source
  // emitted verbatim (its tokens-import rewritten · the descriptors' `./schema`
  // import needs no rewrite — it resolves in both locations).
  await mkdir(DESCRIPTORS_OUT, { recursive: true });
  const schemaSource = await readFile(SCHEMA_SRC, 'utf8');
  await writeFile(resolve(DESCRIPTORS_OUT, 'schema.ts'), emitSchemaTs(schemaSource), 'utf8');
  const descriptorReports = [];
  for (const spec of DESCRIPTOR_COMPONENTS) {
    const source = await readFile(resolve(DESCRIPTORS_SRC, `${spec.name}.ts`), 'utf8');
    const out = resolve(DESCRIPTORS_OUT, `${spec.name}.ts`);
    await writeFile(out, emitDescriptorTsFromSource(spec, source), 'utf8');
    // Browser-ESM twin (decision 67) — the authored .ts type-stripped (the runtime
    // web factory imports it with no build step · zero-build). Gated to
    // BROWSER_DESCRIPTOR_COMPONENTS. Additive (decision 35).
    let browser = false;
    if (BROWSER_DESCRIPTOR_COMPONENTS.includes(spec.name)) {
      await writeFile(resolve(DESCRIPTORS_OUT, `${spec.name}.js`), emitDescriptorJsFromSource(spec, source), 'utf8');
      browser = true;
    }
    descriptorReports.push({ name: spec.name, out, browser });
  }

  // ── Slice 8 · palette mapping emit (N+19 B2b · decision 65.3 §6 · re-sourced N+40) ──
  // ADDITIVE at build/palette.ts: the {variant | chrome} → {bg, fg,
  // fgMuted, pressedBg} table as TokenPath data, emitted ONCE in the
  // baseline (decision 65.2). derivePalette asserts every contract cell
  // against the namespace-axis TS SoTs — palette-surface.ts's `surface`
  // (variant+chrome bg/fg/pressed pairs) + typography-axis.ts's `axis` (the muted
  // dispatch) — before emitting; a contradiction fails the build (decision 48). The
  // witness was RE-SOURCED at N+40 from the generated lib/components/{palette,
  // typography}.css those SoTs emit (§74 'Next: final') so this slice stops reading
  // the namespace CSS the A3 carve relocates — the cells are unchanged (the contract
  // resolves identically; only its witness moved one step up the cascade). The
  // recipe-CSS cross-checks (button/icon-avatar/topbar) retired earlier (decision 74).
  const surface = await loadAxisSoT(PALETTE_SURFACE_SRC, 'surface');
  const typographyAxis = await loadAxisSoT(TYPOGRAPHY_AXIS_SRC, 'axis');
  const paletteCells = derivePalette({ surface, typographyAxis }, { classifiedGroups });
  await writeFile(PALETTE_OUT, emitPaletteTs(paletteCells), 'utf8');
  const paletteRowCount =
    Object.keys(paletteCells.variant).length + Object.keys(paletteCells.chrome).length;

  // (Slice 9 · the component doc page emit · MOVED to @nuri/doc at N+42 · the A4
  // carve. The doc-gen [emitDocPage / buildDocTokenInputs / docIrFromDescriptor]
  // left @nuri/spec — transforming the descriptor + token DATA → Markdown is now
  // @nuri/doc's job (convergence §5 · decision 75 · "spec emits data, doc
  // transforms it"). @nuri/doc re-sources onto @nuri/spec's DATA exports
  // [tokens · token-vars · palette · descriptors/* · the browser-ESM twins Slice 7
  // still emits], NOT this orchestrator's in-memory classifier results, and emits
  // generated/components/<source>.md byte-identical via `npm run build -w @nuri/doc`.
  // build/docs/ is gone; the moved Guard G gates the re-emit in @nuri/doc.)

  console.log(
    `[tokens-parser] wrote ${jsonCount} colour primitives → ${JSON_OUT}\n` +
    `[tokens-parser] wrote ${semanticCount} semantic tokens × ${ACCENTS.length} accents × ${THEMES.length} themes → ${TS_OUT}\n` +
    `[tokens-parser] wrote type scale (${TYPE_SIZES.length} sizes + emphasisWeight · de-fused) → ${TS_OUT}\n` +
    `[tokens-parser] wrote interaction baseline (${Object.keys(INTERACTION_PRIMITIVES).length} constants · transversal) → ${INTERACTION_OUT}` +
    `\n[tokens-parser] wrote TokenPath union → ${TOKEN_PATHS_OUT}` +
    `\n[tokens-parser] wrote semantic colour var registry → ${TOKEN_VARS_OUT}` +
    `\n[tokens-parser] wrote icon registry (${iconNameCount} glyphs · folder SoT · 2 readers) → ${ICONS_JS_OUT} + ${ICONS_OUT}` +
    `\n[tokens-parser] wrote descriptor schema → ${resolve(DESCRIPTORS_OUT, 'schema.ts')}` +
    descriptorReports.map((r) =>
      `\n[tokens-parser] wrote descriptor '${r.name}' (authored SoT${r.browser ? ' + browser ESM' : ''}) → ${r.out}`,
    ).join('') +
    `\n[tokens-parser] wrote palette mapping (${paletteRowCount} rows · SoT-asserted) → ${PALETTE_OUT}`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
